"""Build the 2019-08 → present continuation panel.

The verified real series stops on 2019-07-31, but the product has to demonstrate
on current dates. This writes a *bridge*: a single synthetic continuation that
starts from the real 2019-07-31 levels and evolves with dynamics fitted to the
whole real record.

It is labelled `synthetic_bridge` in every row and is not eligible for scoring.
Its job is to let the application run end-to-end on plausible recent numbers, not
to describe what the market actually did — it does not know about COVID or the
2021 spike, and nothing downstream should imply that it does.
"""
from __future__ import annotations

import argparse
import sys
from datetime import date
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from forecast_v2 import synth
from forecast_v2.dataset import INDEX_COLS, load_real

REAL = "data/processed/real_baltic_multivariate.csv"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--until", default=str(date.today()))
    ap.add_argument("--seed", type=int, default=26006)
    ap.add_argument("--out", default="data/processed/baltic_real_plus_bridge.csv")
    args = ap.parse_args()

    real = load_real(REAL)
    last_date = real["obs_date"].max()
    sessions = pd.bdate_range(last_date + pd.Timedelta(days=1), pd.Timestamp(args.until))
    if len(sessions) == 0:
        raise SystemExit("nothing to bridge")

    cfg = synth.SynthConfig(path_len=len(sessions), burn_in=0, seed=args.seed)
    model = synth.fit(real, cfg)                       # full real record, no future exists
    print(f"VAR({cfg.var_lags}) fitted through {model.fitted_through}; "
          f"bridging {len(sessions)} sessions to {sessions[-1].date()}")

    # Continue from the real endpoint rather than a random level.
    rng = np.random.default_rng(args.seed)
    p, k = cfg.var_lags, len(INDEX_COLS)
    logpx = np.log(real[INDEX_COLS].to_numpy(dtype=float))
    hist = np.diff(logpx, axis=0)[-p:]
    lvl_log = logpx[-1].copy()

    n_blocks = int(np.ceil(len(sessions) / cfg.block_len))
    starts = rng.integers(0, max(1, len(model.residuals) - cfg.block_len), size=n_blocks)
    eps = np.vstack([model.residuals[s:s + cfg.block_len] for s in starts])[:len(sessions)]

    levels = np.zeros((len(sessions), k))
    for t in range(len(sessions)):
        pred = model.intercept.copy()
        for l in range(p):
            pred += model.coefs[l] @ hist[-(l + 1)]
        pull = -cfg.level_reversion * (lvl_log - model.anchor_log)
        step = np.clip(pred + eps[t] + pull, -cfg.max_abs_logret, cfg.max_abs_logret)
        lvl_log = lvl_log + step
        levels[t] = np.exp(lvl_log)
        hist = np.vstack([hist[1:], step])

    bridge = pd.DataFrame(np.round(levels, 2), columns=INDEX_COLS)
    bridge.insert(0, "obs_date", sessions)
    bridge["provenance_tag"] = "synthetic_bridge"
    bridge["source_url"] = "generated by forecast_v2/build_bridge.py (NOT market data)"

    real_out = real.copy()
    real_out["provenance_tag"] = "verified_real_mendeley_cc_by_4.0"
    real_out["source_url"] = "https://doi.org/10.17632/t76ckh2ygg.1"

    combined = pd.concat([real_out, bridge], ignore_index=True)
    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    combined.to_csv(args.out, index=False)
    bridge.to_csv("data/synthetic/bridge_2019_present.csv", index=False)

    print(f"\nwrote {args.out}: {len(real_out):,} real + {len(bridge):,} bridge rows")
    print(combined.groupby("provenance_tag")["obs_date"].agg(["min", "max", "count"]).to_string())
    print("\nbridge endpoint levels:")
    print(bridge[INDEX_COLS].tail(1).T.rename(columns={bridge.index[-1]: "level"}).to_string())
    real_last = real[INDEX_COLS].tail(1).to_numpy()[0]
    print("\nreal 2019-07-31 →  bridge end   (ratio)")
    for c, a, b in zip(INDEX_COLS, real_last, levels[-1]):
        print(f"  {c:11} {a:8.0f} → {b:8.0f}   ({b / a:.2f}×)")


if __name__ == "__main__":
    main()
