from typing import Dict, Any
from pathlib import Path

def generate_cleaning_report(
    audit: Dict[str, Any],
    metrics: Dict[str, Any],
    output_path: Path
) -> str:
    """Generate reproducible CLEANING_REPORT.md from pipeline execution."""
    
    jumps_table_rows = ""
    for j in metrics.get("jump_events", []):
        jumps_table_rows += f"| {j['obs_date']} | {j['prev_value']} | {j['curr_value']} | {j['pct_change']:+.2f}% | Preserved (legitimate market volatility) |\n"
    if not jumps_table_rows:
        jumps_table_rows = "| None | - | - | - | No jumps > threshold identified |\n"
        
    report = f"""# SIH26006 — BPI Dataset Cleaning & Validation Report

## Executive Summary
This report is automatically generated by the modular data pipeline (`ml-work/pipeline/`). It audits the historical Baltic Panamax Index (BPI) dataset, validating date continuity, data types, physical constraints, and price jump discontinuities without hard-coding individual observations.

---

## 1. Dataset Volume & Pipeline Transformation
* **Original Raw Rows (All Indices):** {audit.get('raw_total_rows', 0):,}
* **Filtered Index:** `{audit.get('index_code', 'BPI')}`
* **Filtered Raw Rows:** {audit.get('filtered_index_rows', 0):,}
* **Exact Duplicate Rows Removed:** {audit.get('exact_duplicates_removed', 0)}
* **Conflicting Duplicate Dates:** {audit.get('duplicate_dates_found', 0)}
* **Invalid/Unparseable Dates:** {audit.get('invalid_dates_found', 0)}
* **Cleaned Target Rows:** {audit.get('cleaned_row_count', 0):,}
* **Earliest Observation:** `{audit.get('earliest_date', '')}`
* **Latest Observation:** `{audit.get('latest_date', '')}`

---

## 2. Structural & Statistical Audit
* **Calendar Span:** {metrics.get('min_date')} to {metrics.get('max_date')} ({metrics.get('total_calendar_days', 0):,} calendar days)
* **Actual Trading Days:** {metrics.get('actual_trading_days', 0):,} days
* **Expected Business Days (Mon–Fri):** {metrics.get('expected_business_days', 0):,} days
* **Missing Business Days:** {metrics.get('missing_business_days_count', 0)} days (holidays/non-trading days, zero blind imputation applied)
* **Minimum Value:** {metrics.get('min_bpi', 0):.2f} index points
* **Maximum Value:** {metrics.get('max_bpi', 0):.2f} index points
* **Mean Value:** {metrics.get('mean_bpi', 0):.2f} (Std: {metrics.get('std_bpi', 0):.2f})
* **IQR Thresholds:** Q25 = {metrics.get('q25', 0):.2f}, Q75 = {metrics.get('q75', 0):.2f} (IQR = {metrics.get('q75', 0) - metrics.get('q25', 0):.2f})
* **IQR Upper Bound:** {metrics.get('iqr_upper_bound', 0):.2f}
* **Statistical Outliers Identified:** {metrics.get('iqr_outliers_count', 0)} observations
* **Action on Outliers:** **Intentionally preserved**. BPI index spikes correspond to genuine macro shipping market rallies.

---

## 3. Daily Jump Discontinuities (|Return| > 10%)
The pipeline flags price jumps exceeding 10% in a single trading session:

| Date | Previous Value | Current Value | % Change | Policy Action |
| :--- | :--- | :--- | :--- | :--- |
{jumps_table_rows}
---

## 4. Final Output Schema
The processed output file contains the following schema:
1. `obs_date`: ISO-8601 Date (`YYYY-MM-DD`), monotonically increasing.
2. `index_code`: Baltic sub-index identifier (`BPI`).
3. `bpi_value`: Cleaned dry bulk freight index points (Float64).
4. `tc_avg_usd_day`: Time Charter average in USD/day (Float64).
5. `source_url`: Tracking URI of source generator or provider.
6. `provenance_tag`: Provenance category tag (`synthetic_calibrated_demo` or `official_feed`).

---

## 5. Pipeline Reproducibility Guarantee
Any team member can add, remove, or correct observations in `ml-work/data/raw/` and rerun:
```bash
python ml-work/scripts/run_pipeline.py --input ml-work/data/raw/original_dataset.csv --output ml-work/data/processed/bpi_cleaned.csv
```
The pipeline is fully modular, parameterized, and avoids hard-coding.
"""
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(report)
        
    return report
