import React from 'react';
import { useLanguage } from '../context/LanguageContext';

const HINDI_BADGE_MAP = {
  'Observed': 'सत्यापित (Observed)',
  'Observed (2012–2019)': 'सत्यापित (2012–2019)',
  '2012–2019 Verified': '2012–2019 सत्यापित',
  'Synthetic Extension': 'सिंथेटिक विस्तार (Synthetic)',
  'Synthetic Extension (2020–2026)': 'सिंथेटिक विस्तार (2020–2026)',
  '2020–2026 Synthetic': '2020–2026 सिंथेटिक',
  'Forecast': 'पूर्वानुमान (Forecast)',
  'ML Forecast (2026+)': 'एमएल पूर्वानुमान (2026+)',
  '2026+ Horizon': '2026+ क्षितिज',
  'Derived': 'व्युत्पन्न (Derived)',
  'Assumption': 'मान्यता (Assumption)',
  'Simulation / Demo Data': 'सिमुलेशन / डेमो डेटा',
  'Unavailable': 'अनुपलब्ध',
  'Score: 0–100': 'स्कोर: 0–100',
  'Decision Engine Output': 'निर्णय इंजन आउटपुट',
  'Navigational Authority Records': 'नौवहन प्राधिकरण रिकॉर्ड',
  'Perturbation Sensitivity Weights': 'संवेदनशीलता भार (±1σ)'
};

/**
 * Institutional Provenance Badge
 * Complies with Section 6, 24, and 30 of SIH26006 Specification:
 * - OBSERVED: Green/emerald badge (Measured historical observations 2012–2019)
 * - SYNTHETIC EXTENSION: Purple/indigo badge (Demonstration & experimental environment 2020–2026)
 * - FORECAST: Blue badge (Probabilistic ML forecast horizon)
 * - DERIVED: Slate badge (Calculated by model from measured inputs, e.g. $/tonne)
 * - ASSUMPTION: Amber badge (Hand-curated, expert-set, or user-editable assumptions)
 * - SIMULATED_DEMO: Amber/orange badge (Synthetic demonstration data standing in for credentials)
 */
export default function ProvenanceBadge({ type = 'observed', text, title, className = '' }) {
  const { lang } = useLanguage();
  const isHi = lang === 'hi';
  const normalized = (type || '').toLowerCase();

  let badgeClass = 'bg-slate-100 text-slate-700 border-slate-200';
  let dotColor = 'bg-slate-400';
  let defaultText = isHi ? 'सत्यापित' : 'Observed';
  let defaultTitle = isHi ? 'सत्यापित ऐतिहासिक डेटा' : 'Verified historical data';

  if (normalized.includes('synthetic') || normalized.includes('extension')) {
    badgeClass = 'bg-purple-50 text-purple-800 border-purple-200';
    dotColor = 'bg-purple-600';
    defaultText = isHi ? 'सिंथेटिक विस्तार' : 'Synthetic Extension';
    defaultTitle = isHi ? 'पूर्वानुमान प्रयोगों हेतु 2019 उपरांत अंशांकित विस्तार' : 'Calibrated post-2019 extension for forecasting experiments';
  } else if (normalized.includes('forecast') || normalized.includes('p10') || normalized.includes('p50') || normalized.includes('p90')) {
    badgeClass = 'bg-blue-50 text-blue-800 border-blue-200';
    dotColor = 'bg-blue-600';
    defaultText = isHi ? 'पूर्वानुमान' : 'Forecast';
    defaultTitle = isHi ? 'क्वांटाइल LightGBM मॉडल द्वारा उत्पन्न भावी क्षितिज' : 'Future horizon generated by Quantile LightGBM models';
  } else if (normalized.includes('observed') || normalized.includes('measured') || normalized.includes('real')) {
    badgeClass = 'bg-emerald-50 text-emerald-800 border-emerald-200';
    dotColor = 'bg-emerald-600';
    defaultText = isHi ? 'सत्यापित' : 'Observed';
    defaultTitle = isHi ? 'सत्यापित ऐतिहासिक बाल्टिक डेटा (2012–2019 Mendeley Data)' : 'Verified historical Baltic observations (2012–2019 Mendeley Data)';
  } else if (normalized.includes('derived') || normalized.includes('calculated')) {
    badgeClass = 'bg-slate-100 text-slate-800 border-slate-300';
    dotColor = 'bg-slate-500';
    defaultText = isHi ? 'व्युत्पन्न' : 'Derived';
    defaultTitle = isHi ? 'भौतिक मॉडल से व्युत्पन्न गणना अथवा समुद्री मार्ग रूपांतरण' : 'Engineered calculation or route translation derived from physical models';
  } else if (normalized.includes('assumption') || normalized.includes('expert') || normalized.includes('user_editable')) {
    badgeClass = 'bg-amber-50 text-amber-800 border-amber-200';
    dotColor = 'bg-amber-500';
    defaultText = isHi ? 'मान्यता' : 'Assumption';
    defaultTitle = isHi ? 'परिचालन अथवा व्यावसायिक मान्यता' : 'Operational or commercial assumption from assumptions register';
  } else if (normalized.includes('demo') || normalized.includes('simulated')) {
    badgeClass = 'bg-amber-50 text-amber-900 border-amber-300';
    dotColor = 'bg-amber-600';
    defaultText = isHi ? 'सिमुलेशन / डेमो' : 'Simulation / Demo Data';
    defaultTitle = isHi ? 'स्वामित्व वाली लाइव फीड हेतु अंशांकित प्रदर्शन डेटासेट' : 'Calibrated demonstration dataset standing in for proprietary live feed';
  } else if (normalized.includes('unavailable') || normalized.includes('pending')) {
    badgeClass = 'bg-slate-100 text-slate-500 border-slate-200';
    dotColor = 'bg-slate-400';
    defaultText = isHi ? 'अनुपलब्ध' : 'Unavailable';
    defaultTitle = isHi ? 'इस संयोजन के लिए डेटा उपलब्ध नहीं है' : 'Data not available for this combination';
  }

  const displayText = isHi && text ? (HINDI_BADGE_MAP[text] || text) : (text || defaultText);

  return (
    <span 
      title={title || defaultTitle}
      className={`inline-flex items-center px-1.5 py-0.5 rounded text-[10px] font-medium border cursor-help select-none ${badgeClass} ${className}`}
    >
      <span className={`w-1.5 h-1.5 rounded-full ${dotColor} mr-1 flex-shrink-0`} />
      <span>{displayText}</span>
    </span>
  );
}
