import React from 'react';

/**
 * Institutional Provenance Badge
 * Complies with Section 6, 24, and 30 of SIH26006 Specification:
 * - OBSERVED: Green/emerald badge (Measured historical observations 2012–2019)
 * - SYNTHETIC EXTENSION: Purple/indigo badge (Demonstration & experimental environment 2020–2026)
 * - FORECAST: Blue badge (Probabilistic ML forecast horizon)
 * - DERIVED: Slate badge (Calculated by model from measured inputs, e.g. $/tonne)
 * - ASSUMPTION: Amber badge (Hand-curated, expert-set, or user-editable assumptions)
 * - SIMULATED_DEMO: Amber/orange badge (Synthetic demonstration data standing in for credentials)
 */
export default function ProvenanceBadge({ type = 'observed', text, title, className = '' }) {
  const normalized = (type || '').toLowerCase();

  let badgeClass = 'bg-slate-100 text-slate-700 border-slate-200';
  let dotColor = 'bg-slate-400';
  let defaultText = 'Observed';
  let defaultTitle = 'Verified historical data';

  if (normalized.includes('synthetic') || normalized.includes('extension')) {
    badgeClass = 'bg-purple-50 text-purple-800 border-purple-200';
    dotColor = 'bg-purple-600';
    defaultText = 'Synthetic Extension';
    defaultTitle = 'Calibrated post-2019 extension for forecasting experiments';
  } else if (normalized.includes('forecast') || normalized.includes('p10') || normalized.includes('p50') || normalized.includes('p90')) {
    badgeClass = 'bg-blue-50 text-blue-800 border-blue-200';
    dotColor = 'bg-blue-600';
    defaultText = 'Forecast';
    defaultTitle = 'Future horizon generated by Quantile LightGBM models';
  } else if (normalized.includes('observed') || normalized.includes('measured') || normalized.includes('real')) {
    badgeClass = 'bg-emerald-50 text-emerald-800 border-emerald-200';
    dotColor = 'bg-emerald-600';
    defaultText = 'Observed';
    defaultTitle = 'Verified historical Baltic observations (2012–2019 Mendeley Data)';
  } else if (normalized.includes('derived') || normalized.includes('calculated')) {
    badgeClass = 'bg-slate-100 text-slate-800 border-slate-300';
    dotColor = 'bg-slate-500';
    defaultText = 'Derived';
    defaultTitle = 'Engineered calculation or route translation derived from physical models';
  } else if (normalized.includes('assumption') || normalized.includes('expert') || normalized.includes('user_editable')) {
    badgeClass = 'bg-amber-50 text-amber-800 border-amber-200';
    dotColor = 'bg-amber-500';
    defaultText = 'Assumption';
    defaultTitle = 'Operational or commercial assumption from assumptions register';
  } else if (normalized.includes('demo') || normalized.includes('simulated')) {
    badgeClass = 'bg-amber-50 text-amber-900 border-amber-300';
    dotColor = 'bg-amber-600';
    defaultText = 'Simulation / Demo Data';
    defaultTitle = 'Calibrated demonstration dataset standing in for proprietary live feed';
  } else if (normalized.includes('unavailable') || normalized.includes('pending')) {
    badgeClass = 'bg-slate-100 text-slate-500 border-slate-200';
    dotColor = 'bg-slate-400';
    defaultText = 'Unavailable';
    defaultTitle = 'Data not available for this combination';
  }

  return (
    <span 
      title={title || defaultTitle}
      className={`inline-flex items-center px-1.5 py-0.5 rounded text-[10px] font-medium border cursor-help select-none ${badgeClass} ${className}`}
    >
      <span className={`w-1.5 h-1.5 rounded-full ${dotColor} mr-1 flex-shrink-0`} />
      <span>{text || defaultText}</span>
    </span>
  );
}
